In [1]:
import pandas as pd

companies = pd.read_excel("companies.xlsx")
print(companies.columns.tolist())

balance = pd.read_excel("balancesheet.xlsx")
print(balance.columns.tolist())

pl = pd.read_excel("profitandloss.xlsx")
print(pl.columns.tolist())

['Mkt Fintech — Nifty 100  |  Companies  |  92 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11']
['Bluestock Fintech — Nifty 100  |  Balance Sheet  |  1,312 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']
['Bluestock Fintech — Nifty 100  |  Profit & Loss  |  1,276 records', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']

In [2]:
import pandas as pd

companies = pd.read_excel("companies.xlsx", header=None)

print(companies.head(15))

                                                   0   \
0   Mkt Fintech — Nifty 100  |  Companies  |  92 r...
1                                                  id
2                                                 ABB
3                                          ADANIENSOL
4                                            ADANIENT
5                                          ADANIGREEN
6                                          ADANIPORTS
7                                          ADANIPOWER
8                                           AMBUJACEM
9                                          APOLLOHOSP
10                                         ASIANPAINT
11                                               ATGL
12                                           AXISBANK
13                                         BAJAJ-AUTO
14                                         BAJAJFINSV

                                                   1   \
0                                                 NaN
1                                        company_logo
2    https://mkt.in/static/mkt-icons/nifty100/ABB.png
3   https://m.economictimes.com/thumb/msid-1173715...
4   https://mkt.in/static/mkt-icons/nifty100/ADANI...
5   https://mkt.in/static/mkt-icons/nifty100/ADANI...
6   https://mkt.in/static/mkt-icons/nifty100/ADANI...
7   https://mkt.in/static/mkt-icons/nifty100/ADANI...
8   https://mkt.in/static/mkt-icons/nifty100/AMBUJ...
9   https://mkt.in/static/mkt-icons/nifty100/APOLL...
10  https://mkt.in/static/mkt-icons/nifty100/ASIAN...
11  https://mkt.in/static/mkt-icons/nifty100/ATGL.png
12  https://mkt.in/static/mkt-icons/nifty100/AXISB...
13  https://mkt.in/static/mkt-icons/nifty100/BAJAJ...
14  https://mkt.in/static/mkt-icons/nifty100/BAJAJ...

                                                   2   \
0                                                 NaN
1                                        company_name
2                                    Abbott India Ltd
3                          Adani Energy Solutions Ltd
4                               Adani Enterprises Ltd
5                              Adani Green Energy Ltd
6           Adani Ports & Special Economic Zone Ltd\n
7                                     Adani Power Ltd
8                                  Ambuja Cements Ltd
9   Apollo Hospitals\nChain of Indian private hosp...
10  Asian Paints\nIndian Multi-National Paint and ...
11                                Adani Total Gas Ltd
12                                      Axis Bank Ltd
13                                     Bajaj Auto Ltd
14                                  Bajaj Finserv Ltd

                                                   3   \
0                                                 NaN
1                                          chart_link
2   https://in.tradingview.com/chart/?symbol=NSE%3...
3   https://in.tradingview.com/chart/?symbol=NSE%3...
4   https://in.tradingview.com/chart/?symbol=ADANIENT
5   https://in.tradingview.com/chart/?symbol=NSE%3...
6   https://in.tradingview.com/chart/?symbol=NSE%3...
7   https://in.tradingview.com/chart/?symbol=NSE%3...
8   https://in.tradingview.com/chart/qGsydD2w/?sym...
9   https://in.tradingview.com/chart/?symbol=NSE%3...
10  https://in.tradingview.com/chart/?symbol=NSE%3...
11  https://in.tradingview.com/chart/?symbol=NSE%3...
12  https://in.tradingview.com/chart/?symbol=NSE%3...
13  https://in.tradingview.com/chart/qGsydD2w/?sym...
14  https://in.tradingview.com/chart/?symbol=NSE%3...

                                                   4   \
0                                                 NaN
1                                       about_company
2   Abbott India Ltd is one of the leading multina...
3   AESL, part of the Adani portfolio, is a multid...
4   Adani Enterprises Ltd is an Indian multination...
5   Adani Green Energy Limited, incorporated in 20...
6   Adani Ports & Special Economic Zone is in the ...
7   Adani Power (APL), a part of the diversified A...
8   Ambuja Cements Ltd. is among the leading cemen...
9   Apollo Hospitals Enterprise Limited is an Indi...
10  Asian Paints Ltd is an Indian multinational pa...
11  AGL is engaged in City Gas Distribution (CGD) ...
12  Incorporated in December 1993, Axis Bank Limit...
13  Bajaj Auto, the flagship company of Bajaj Grou...
14  Bajaj Finserv Limited is an Indian non-banking...

                                       5   \
0                                     NaN
1                                 website
2               https://www.abbott.co.in/
3   https://www.adanienergysolutions.com/
4       https://www.adanienterprises.com/
5        http://www.adanigreenenergy.com/
6              http://www.adaniports.com/
7                   http://www.adani.com/
8           https://www.ambujacement.com/
9        https://www.apollohospitals.com/
10           https://www.asianpaints.com/
11               http://www.adanigas.com/
12               http://www.axisbank.com/
13             https://www.bajajauto.com/
14           https://www.bajajfinserv.in/

                                                   6   \
0                                                 NaN
1                                         nse_profile
2   https://www.nseindia.com/get-quotes/equity?sym...
3   https://www.nseindia.com/get-quotes/equity?sym...
4   https://www.nseindia.com/get-quotes/equity?sym...
5   https://www.nseindia.com/get-quotes/equity?sym...
6   https://www.nseindia.com/get-quotes/equity?sym...
7   https://www.nseindia.com/get-quotes/equity?sym...
8   https://www.nseindia.com/get-quotes/equity?sym...
9   https://www.nseindia.com/get-quotes/equity?sym...
10  https://www.nseindia.com/get-quotes/equity?sym...
11  https://www.nseindia.com/get-quotes/equity?sym...
12  https://www.nseindia.com/get-quotes/equity?sym...
13  https://www.nseindia.com/get-quotes/equity?sym...
14  https://www.nseindia.com/get-quotes/equity?sym...

                                                   7           8           9   \
0                                                 NaN         NaN         NaN
1                                         bse_profile  face_value  book_value
2   https://www.bseindia.com/stock-share-price/abb...          10        1657
3   https://www.bseindia.com/stock-share-price/ada...          10         175
4   https://www.bseindia.com/stock-share-price/ada...           1         363
5   https://www.bseindia.com/stock-share-price/ada...          10          67
6   https://www.bseindia.com/stock-share-price/ada...           2         265
7   https://www.bseindia.com/stock-share-price/ada...          10         145
8   https://www.bseindia.com/stock-share-price/amb...           2         205
9   https://www.bseindia.com/stock-share-price/apo...           5         522
10  https://www.bseindia.com/stock-share-price/asi...           1         188
11  https://www.bseindia.com/stock-share-price/ada...           1          36
12  https://www.bseindia.com/stock-share-price/axi...           2         509
13  https://www.bseindia.com/stock-share-price/baj...          10        1109
14  https://www.bseindia.com/stock-share-price/baj...           1         428

                 10              11
0               NaN             NaN
1   roce_percentage  roe_percentage
2                46            34.9
3                 9            8.59
4              11.6           13.64
5              96.5            14.7
6              12.9            18.1
7              32.2            57.1
8              12.8            9.24
9              17.2           13.81
10            41.75           31.45
11             21.2            20.5
12             7.06            18.4
13             33.5            26.5
14            21.14           11.72

In [3]:
balance = pd.read_excel("balancesheet.xlsx", header=None)
print(balance.head(15))

                                                   0           1         2   \
0   Bluestock Fintech — Nifty 100  |  Balance Shee...         NaN       NaN
1                                                  id  company_id      year
2                                                 136         ABB  Dec 2012
3                                                 137         ABB  Mar 2014
4                                                 138         ABB  Mar 2015
5                                                 139         ABB  Mar 2016
6                                                 140         ABB  Mar 2017
7                                                 141         ABB  Mar 2018
8                                                 142         ABB  Mar 2019
9                                                 143         ABB  Mar 2020
10                                                144         ABB  Mar 2021
11                                                145         ABB  Mar 2022
12                                                146         ABB  Mar 2023
13                                                147         ABB  Mar 2024
14                                                148         ABB  Sep 2024

                3         4           5                  6   \
0              NaN       NaN         NaN                NaN
1   equity_capital  reserves  borrowings  other_liabilities
2               21       626           0                260
3               21       767           0                351
4               21       916           0                436
5               21      1174           0                421
6               21      1366           0                679
7               21      1672           0                723
8               21      1987           0                932
9               21      2410         175                940
10              21      2581         153               1086
11              21      2799         152               1253
12              21      3167         113               1254
13              21      3678          83               1411
14              21      3500          60               1481

                   7             8     9            10           11  \
0                 NaN           NaN   NaN          NaN          NaN
1   total_liabilities  fixed_assets  cwip  investments  other_asset
2                 907           109     1            0          798
3                1139            98     1            0         1040
4                1374            96     4            0         1274
5                1616           108     3            0         1505
6                2066           110     6            0         1950
7                2416            81     2            0         2333
8                2941           105     1            0         2835
9                3547           270     2            0         3275
10               3840           251     1            0         3589
11               4224           271     1            0         3952
12               4556           237     4            0         4315
13               5193           225    10            0         4958
14               5063           216    13            0         4834

              12
0            NaN
1   total_assets
2            907
3           1139
4           1374
5           1616
6           2066
7           2416
8           2941
9           3547
10          3840
11          4224
12          4556
13          5193
14          5063

In [4]:
pl = pd.read_excel("profitandloss.xlsx", header=None)
print(pl.head(15))

                                                   0           1         2   \
0   Bluestock Fintech — Nifty 100  |  Profit & Los...         NaN       NaN
1                                                  id  company_id      year
2                                                  61         ABB  Dec 2012
3                                                  62         ABB  Mar 2014
4                                                  63         ABB  Mar 2015
5                                                  64         ABB  Mar 2016
6                                                  65         ABB  Mar 2017
7                                                  66         ABB  Mar 2018
8                                                  67         ABB  Mar 2019
9                                                  68         ABB  Mar 2020
10                                                 69         ABB  Mar 2021
11                                                 70         ABB  Mar 2022
12                                                 71         ABB  Mar 2023
13                                                 72         ABB  Mar 2024
14                                                 73         ABB       TTM

       3         4                 5               6             7         8   \
0     NaN       NaN               NaN             NaN           NaN       NaN
1   sales  expenses  operating_profit  opm_percentage  other_income  interest
2    1653      1451               202              12            33         0
3    2276      2009               267              12            49         0
4    2289      1977               312              14            48         0
5    2614      2250               365              14            50         3
6    2903      2505               398              14            57         2
7    3298      2774               525              16           117         4
8    3679      3074               605              16           113         2
9    4093      3336               757              18           114         9
10   4310      3388               922              21            81        18
11   4913      3832              1082              22            83        19
12   5349      4143              1206              23           154        16
13   5849      4396              1453              25           248        12
14   6066      4519              1547              26           265        11

              9                  10              11          12   13  \
0            NaN                NaN             NaN         NaN  NaN
1   depreciation  profit_before_tax  tax_percentage  net_profit  eps
2             19                215              33         145   68
3             22                295              33         198   93
4             15                344              34         229  108
5             14                398              36         255  120
6             16                436              37         277  130
7             16                621              35         401  189
8             17                699              36         450  212
9             60                803              26         593  279
10            58                926              25         691  325
11            66               1080              26         799  376
12            70               1274              25         949  447
13            71               1618              26        1201  565
14            72               1728             NaN        1285  605

                 14
0               NaN
1   dividend_payout
2                25
3                25
4                29
5                29
6                31
7                29
8                31
9                90
10               85
11               73
12               73
13               73
14              NaN

In [8]:
import pandas as pd

# -------------------------------
# File Paths
# -------------------------------
companies_path = "companies.xlsx"
balance_path = "balancesheet.xlsx"
profit_loss_path = "profitandloss.xlsx"

# -------------------------------
# Function to find the header row
# -------------------------------
def find_header(file_path, keyword):
    df = pd.read_excel(file_path, header=None)

    for i in range(len(df)):
        row = df.iloc[i].astype(str).str.lower()

        if keyword.lower() in row.values:
            print(f"\nHeader found in {file_path} at row {i}")
            return i

    print(f"\nHeader not found in {file_path}")
    return None

# -------------------------------
# Find header rows
# -------------------------------
companies_header = find_header(companies_path, "company_id")
balance_header = find_header(balance_path, "company_id")
profit_header = find_header(profit_loss_path, "company_id")

# -------------------------------
# Load datasets using detected headers
# -------------------------------
companies = pd.read_excel(companies_path, header=companies_header)
balance = pd.read_excel(balance_path, header=balance_header)
profit_loss = pd.read_excel(profit_loss_path, header=profit_header)

# -------------------------------
# Display column names
# -------------------------------
print("\nCompanies Columns:")
print(companies.columns.tolist())

print("\nBalance Sheet Columns:")
print(balance.columns.tolist())

print("\nProfit & Loss Columns:")
print(profit_loss.columns.tolist())

Header not found in companies.xlsx

Header found in balancesheet.xlsx at row 1

Header found in profitandloss.xlsx at row 1

Companies Columns:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

Balance Sheet Columns:
['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets']

Profit & Loss Columns:
['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']

In [18]:
ratio_data = pd.read_excel("companies.xlsx", header=1)
print(ratio_data.columns.tolist())

['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']

In [24]:
rd=pd.read_excel("sectors.xlsx")
#ff=pd.read_excel( "companies.xlsx")
ratio_data = pd.read_excel("companies.xlsx", header=1)

# Rename id to company_id
ratio_data.rename(columns={"id": "company_id"}, inplace=True)

# Keep only required columns
ratio_data = ratio_data[
    ["company_id", "company_name", "roce_percentage", "roe_percentage"]
]
rd =rd[
    ["company_id", "broad_sector"]
]

companies = pd.merge(
    rd,
    ratio_data,
    on="company_id",
    how="left"
)

In [25]:
display(companies)

,company_id,broad_sector,company_name,roce_percentage,roe_percentage
0,ABB,Industrials,Abbott India Ltd,46.0,34.90
1,ADANIENSOL,Energy,Adani Energy Solutions Ltd,9.0,8.59
2,ADANIENT,Industrials,Adani Enterprises Ltd,11.6,13.64
3,ADANIGREEN,Energy,Adani Green Energy Ltd,96.5,14.70
4,ADANIPORTS,Industrials,Adani Ports & Special Economic Zone Ltd\n,12.9,18.10
...,...,...,...,...,...
87,TECHM,Information Technology,Tech Mahindra Ltd,11.9,8.63
88,TITAN,Consumer Discretionary,Titan Company Ltd\n,22.7,32.90
89,TORNTPHARM,Healthcare,Torrent Pharmaceuticals Ltd,23.2,24.20
90,TRENT,Consumer Discretionary,Trent Ltd,23.8,27.20
91,TVSMOTOR,Consumer Discretionary,TVS Motor Company Ltd,NaN,NaN

In [35]:
import pandas as pd

# Load datasets
balance_sheet = pd.read_excel("balancesheet.xlsx", header=1)
profit_loss = pd.read_excel("profitandloss.xlsx", header=1)

# Merge on company_id and year
financial_data = pd.merge(
    balance_sheet,
    profit_loss,
    on=["company_id", "year"],
    how="inner"
)

# Display the merged data
display(financial_data.head())

,id_x,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,...,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,136,ABB,Dec 2012,21.0,626,0,260,907,109,1,...,202.0,12.0,33,0,19,215,33.0,145,68.0,25.0
1,137,ABB,Mar 2014,21.0,767,0,351,1139,98,1,...,267.0,12.0,49,0,22,295,33.0,198,93.0,25.0
2,138,ABB,Mar 2015,21.0,916,0,436,1374,96,4,...,312.0,14.0,48,0,15,344,34.0,229,108.0,29.0
3,139,ABB,Mar 2016,21.0,1174,0,421,1616,108,3,...,365.0,14.0,50,3,14,398,36.0,255,120.0,29.0
4,140,ABB,Mar 2017,21.0,1366,0,679,2066,110,6,...,398.0,14.0,57,2,16,436,37.0,277,130.0,31.0

In [36]:
# Load datasets
balance_sheet = pd.read_excel("balancesheet.xlsx", header=1)
profit_loss = pd.read_excel("profitandloss.xlsx", header=1)

# Merge on company_id and year
financial_data1 = pd.merge(
    companies,
    financial_data,
    on=["company_id"],
    how="inner"
)

# Display the merged data
display(financial_data1.head())

,company_id,broad_sector,company_name,roce_percentage,roe_percentage,id_x,year,equity_capital,reserves,borrowings,...,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
0,ABB,Industrials,Abbott India Ltd,46.0,34.9,136,Dec 2012,21.0,626,0,...,202.0,12.0,33,0,19,215,33.0,145,68.0,25.0
1,ABB,Industrials,Abbott India Ltd,46.0,34.9,137,Mar 2014,21.0,767,0,...,267.0,12.0,49,0,22,295,33.0,198,93.0,25.0
2,ABB,Industrials,Abbott India Ltd,46.0,34.9,138,Mar 2015,21.0,916,0,...,312.0,14.0,48,0,15,344,34.0,229,108.0,29.0
3,ABB,Industrials,Abbott India Ltd,46.0,34.9,139,Mar 2016,21.0,1174,0,...,365.0,14.0,50,3,14,398,36.0,255,120.0,29.0
4,ABB,Industrials,Abbott India Ltd,46.0,34.9,140,Mar 2017,21.0,1366,0,...,398.0,14.0,57,2,16,436,37.0,277,130.0,31.0

In [37]:
import pandas as pd
import numpy as np
import os

# =====================================================
# DAY 13 - Bank ROCE Carve-Out & Edge Case Validation
# =====================================================

# Use merged dataset
df = financial_data1.copy()

# -----------------------------
# Calculate Net Worth
# -----------------------------
df["net_worth"] = df["equity_capital"] + df["reserves"]

# -----------------------------
# Calculate Capital Employed
# -----------------------------
df["capital_employed"] = df["total_assets"] - df["other_liabilities"]

# Avoid divide-by-zero
df["net_worth"] = df["net_worth"].replace(0, np.nan)
df["capital_employed"] = df["capital_employed"].replace(0, np.nan)

# -----------------------------
# Compute ROCE
# Formula:
# Operating Profit / Capital Employed * 100
# -----------------------------
df["computed_roce"] = (
    df["operating_profit"] /
    df["capital_employed"]
) * 100

# -----------------------------
# Compute ROE
# Formula:
# Net Profit / Net Worth * 100
# -----------------------------
df["computed_roe"] = (
    df["net_profit"] /
    df["net_worth"]
) * 100

# -----------------------------
# Debt-to-Equity Ratio
# -----------------------------
df["de_ratio"] = (
    df["borrowings"] /
    df["net_worth"]
)

# -----------------------------
# D/E Warning
# -----------------------------
df["de_warning"] = np.where(
    df["de_ratio"] > 2,
    "High Debt",
    "Normal"
)

# Suppress D/E warning for Financial companies
financial_mask = (
    df["broad_sector"]
    .astype(str)
    .str.lower()
    .str.contains("financial")
)

df.loc[
    financial_mask,
    "de_warning"
] = "Suppressed (Financial Sector)"

# -----------------------------
# Compare with Source Ratios
# -----------------------------
df["roce_difference"] = (
    df["computed_roce"] -
    df["roce_percentage"]
).abs()

df["roe_difference"] = (
    df["computed_roe"] -
    df["roe_percentage"]
).abs()

# -----------------------------
# Find Edge Cases
# -----------------------------
edge_cases = df[
    (df["roce_difference"] > 5) |
    (df["roe_difference"] > 5)
].copy()

# -----------------------------
# Categorise Edge Cases
# -----------------------------
def categorize(row):

    if (
        pd.isna(row["roce_percentage"])
        or pd.isna(row["roe_percentage"])
        or row["roe_percentage"] < 1
        or row["roce_percentage"] < 1
    ):
        return "Data Source Issue"

    elif (
        row["roce_difference"] > 5
        and row["roe_difference"] > 5
    ):
        return "Formula Discrepancy"

    else:
        return "Version Difference"

edge_cases["category"] = edge_cases.apply(
    categorize,
    axis=1
)

# -----------------------------
# Create Output Folder
# -----------------------------
os.makedirs("output", exist_ok=True)

# -----------------------------
# Save Log File
# -----------------------------
with open(
    "output/ratio_edge_cases.log",
    "w",
    encoding="utf-8"
) as log:

    log.write("DAY 13 - RATIO EDGE CASES\n")
    log.write("=" * 80 + "\n\n")

    for _, row in edge_cases.iterrows():

        log.write(f"Company Name : {row['company_name']}\n")
        log.write(f"Company ID   : {row['company_id']}\n")
        log.write(f"Year         : {row['year']}\n")
        log.write(f"Sector       : {row['broad_sector']}\n\n")

        log.write(
            f"Computed ROCE : {row['computed_roce']:.2f}\n"
        )
        log.write(
            f"Source ROCE   : {row['roce_percentage']:.2f}\n"
        )
        log.write(
            f"Difference    : {row['roce_difference']:.2f}\n\n"
        )

        log.write(
            f"Computed ROE  : {row['computed_roe']:.2f}\n"
        )
        log.write(
            f"Source ROE    : {row['roe_percentage']:.2f}\n"
        )
        log.write(
            f"Difference    : {row['roe_difference']:.2f}\n\n"
        )

        log.write(
            f"D/E Ratio     : {row['de_ratio']:.2f}\n"
        )
        log.write(
            f"D/E Warning   : {row['de_warning']}\n"
        )

        log.write(
            f"Category      : {row['category']}\n"
        )

        log.write("-" * 80 + "\n")

# -----------------------------
# Display Summary
# -----------------------------
print("=" * 60)
print("DAY 13 COMPLETED SUCCESSFULLY")
print("=" * 60)

print("Total Records :", len(df))
print("Financial Companies :", financial_mask.sum())
print("Edge Cases Found :", len(edge_cases))
print("Log File Saved : output/ratio_edge_cases.log")

# Display edge cases
display(
    edge_cases[
        [
            "company_name",
            "company_id",
            "year",
            "computed_roce",
            "roce_percentage",
            "computed_roe",
            "roe_percentage",
            "de_warning",
            "category",
        ]
    ]
)

============================================================
DAY 13 COMPLETED SUCCESSFULLY
============================================================
Total Records : 1151
Financial Companies : 294
Edge Cases Found : 798
Log File Saved : output/ratio_edge_cases.log

,company_name,company_id,year,computed_roce,roce_percentage,computed_roe,roe_percentage,de_warning,category
0,Abbott India Ltd,ABB,Dec 2012,31.221020,46.0,22.411128,34.9,Normal,Formula Discrepancy
1,Abbott India Ltd,ABB,Mar 2014,33.883249,46.0,25.126904,34.9,Normal,Formula Discrepancy
2,Abbott India Ltd,ABB,Mar 2015,33.262260,46.0,24.439701,34.9,Normal,Formula Discrepancy
3,Abbott India Ltd,ABB,Mar 2016,30.543933,46.0,21.338912,34.9,Normal,Formula Discrepancy
4,Abbott India Ltd,ABB,Mar 2017,28.695025,46.0,19.971161,34.9,Normal,Formula Discrepancy
...,...,...,...,...,...,...,...,...,...
1134,Trent Ltd,TRENT,Mar 2020,19.680060,23.8,4.438861,27.2,Normal,Version Difference
1135,Trent Ltd,TRENT,Mar 2021,4.362801,23.8,-7.825335,27.2,Normal,Formula Discrepancy
1136,Trent Ltd,TRENT,Mar 2022,8.393285,23.8,1.480541,27.2,Normal,Formula Discrepancy
1137,Trent Ltd,TRENT,Mar 2023,15.779037,23.8,15.177196,27.2,Normal,Formula Discrepancy
1138,Trent Ltd,TRENT,Mar 2024,33.860161,23.8,36.307768,27.2,Normal,Formula Discrepancy

In [43]:
strip2=edge_cases.to_csv("strip2 final dataset.csv")

In [45]:
import numpy as np

df = financial_data1.copy()

# Net Worth
df["net_worth"] = df["equity_capital"] + df["reserves"]

# Capital Employed
df["capital_employed"] = df["total_assets"] - df["other_liabilities"]

# Replace zero with NaN
df["net_worth"] = df["net_worth"].replace(0, np.nan)
df["capital_employed"] = df["capital_employed"].replace(0, np.nan)

# ROCE
df["computed_roce"] = (
    df["operating_profit"] /
    df["capital_employed"]
) * 100

# ROE
df["computed_roe"] = (
    df["net_profit"] /
    df["net_worth"]
) * 100

# Debt to Equity
df["de_ratio"] = (
    df["borrowings"] /
    df["net_worth"]
)

# D/E Warning
df["de_warning"] = np.where(
    df["de_ratio"] > 1,
    "High Debt",
    "Normal"
)

# Suppress for Financial companies
df.loc[
    df["broad_sector"] == "Financials",
    "de_warning"
] = "Suppressed"

# Save back
financial_data1 = df

print("Calculated columns created successfully!")

Calculated columns created successfully!

In [46]:
print(financial_data1.columns.tolist())

['company_id', 'broad_sector', 'company_name', 'roce_percentage', 'roe_percentage', 'id_x', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets', 'id_y', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout', 'net_worth', 'capital_employed', 'computed_roce', 'computed_roe', 'de_ratio', 'de_warning']

In [47]:
import pandas as pd
import os

print("="*80)
print("DAY 14 - TESTS & SPRINT REVIEW")
print("="*80)

# -----------------------------------------------------
# Load merged dataset
# -----------------------------------------------------
df = financial_data1.copy()

# Remove unwanted columns if present
df = df.drop(columns=["id_x","id_y"], errors="ignore")

# -----------------------------------------------------
# KPI UNIT TESTS
# -----------------------------------------------------

tests = []

def add_test(name, condition):
    tests.append([name, "PASS" if condition else "FAIL"])

# Column Tests
required_columns = [
    "company_id",
    "company_name",
    "broad_sector",
    "computed_roce",
    "computed_roe",
    "de_ratio",
    "de_warning",
    "capital_employed",
    "net_worth",
    "roce_percentage",
    "roe_percentage",
    "operating_profit",
    "net_profit",
    "borrowings",
    "equity_capital",
    "reserves",
    "total_assets",
    "other_liabilities"
]

for col in required_columns:
    add_test(f"{col} exists", col in df.columns)

# Value Tests
add_test("ROCE contains values", df["computed_roce"].notna().sum() > 0)
add_test("ROE contains values", df["computed_roe"].notna().sum() > 0)

passed = sum(t[1] == "PASS" for t in tests)
failed = sum(t[1] == "FAIL" for t in tests)

print("\nKPI UNIT TEST RESULTS")
print("-"*80)

for t in tests:
    print(f"{t[1]:5} : {t[0]}")

print("-"*80)
print(f"Passed : {passed}")
print(f"Failed : {failed}")

# -----------------------------------------------------
# EDGE CASE LOG REVIEW
# -----------------------------------------------------

print("\nEDGE CASE LOG REVIEW")
print("-"*80)

log_path = "output/ratio_edge_cases.log"

if os.path.exists(log_path):
    with open(log_path, "r", encoding="utf-8") as f:
        log = f.read()

    print("ratio_edge_cases.log found")
    print(f"Characters : {len(log)}")

    if len(log.strip()) > 0:
        print("All anomalies documented.")
    else:
        print("Log file is empty.")
else:
    print("ratio_edge_cases.log not found.")

# -----------------------------------------------------
# SCREENER PREVIEW
# -----------------------------------------------------

print("\nSCREENER PREVIEW")
print("-"*80)

screener = df[
    (df["computed_roe"] > 15) &
    (df["de_ratio"] < 1)
]

print(f"Companies Found : {len(screener)}")

if 15 <= len(screener) <= 50:
    print("PASS : Count within expected range")
else:
    print("WARNING : Count outside expected range")

print("\nTop Companies")

display(
    screener[
        [
            "company_name",
            "computed_roe",
            "de_ratio",
            "computed_roce"
        ]
    ].head(20)
)

# -----------------------------------------------------
# SPRINT RETROSPECTIVE
# -----------------------------------------------------

print("\nSPRINT 2 RETROSPECTIVE")
print("-"*80)

retrospective = pd.DataFrame({
    "Formula":[
        "ROCE",
        "ROE",
        "Debt to Equity",
        "Capital Employed",
        "Net Worth"
    ],
    "Decision":[
        "Operating Profit / Capital Employed ×100",
        "Net Profit / Net Worth ×100",
        "Borrowings / Net Worth",
        "Total Assets - Other Liabilities",
        "Equity Capital + Reserves"
    ],
    "Edge Case":[
        "Compared with source values",
        "Source values retained for display",
        "Suppressed for Financial companies",
        "Zero handled safely",
        "Zero handled safely"
    ]
})

display(retrospective)

# -----------------------------------------------------
# DEMO TO TEAM LEAD
# -----------------------------------------------------

print("\nFINANCIAL RATIOS DEMO")
print("-"*80)

demo = df[
    [
        "company_name",
        "computed_roce",
        "computed_roe",
        "de_ratio",
        "de_warning"
    ]
].head(5)

display(demo)

# -----------------------------------------------------
# SAVE DEMO
# -----------------------------------------------------

os.makedirs("output", exist_ok=True)

demo.to_csv("output/financial_ratios_demo.csv", index=False)

print("\nfinancial_ratios_demo.csv saved.")

print("\n" + "="*80)
print("DAY 14 COMPLETED SUCCESSFULLY")
print("="*80)

================================================================================
DAY 14 - TESTS & SPRINT REVIEW
================================================================================

KPI UNIT TEST RESULTS
--------------------------------------------------------------------------------
PASS  : company_id exists
PASS  : company_name exists
PASS  : broad_sector exists
PASS  : computed_roce exists
PASS  : computed_roe exists
PASS  : de_ratio exists
PASS  : de_warning exists
PASS  : capital_employed exists
PASS  : net_worth exists
PASS  : roce_percentage exists
PASS  : roe_percentage exists
PASS  : operating_profit exists
PASS  : net_profit exists
PASS  : borrowings exists
PASS  : equity_capital exists
PASS  : reserves exists
PASS  : total_assets exists
PASS  : other_liabilities exists
PASS  : ROCE contains values
PASS  : ROE contains values
--------------------------------------------------------------------------------
Passed : 20
Failed : 0

EDGE CASE LOG REVIEW
--------------------------------------------------------------------------------
ratio_edge_cases.log found
Characters : 331817
All anomalies documented.

SCREENER PREVIEW
--------------------------------------------------------------------------------
Companies Found : 436
WARNING : Count outside expected range

Top Companies

,company_name,computed_roe,de_ratio,computed_roce
0,Abbott India Ltd,22.411128,0.000000,31.221020
1,Abbott India Ltd,25.126904,0.000000,33.883249
2,Abbott India Ltd,24.439701,0.000000,33.262260
3,Abbott India Ltd,21.338912,0.000000,30.543933
4,Abbott India Ltd,19.971161,0.000000,28.695025
5,Abbott India Ltd,23.685765,0.000000,31.010041
6,Abbott India Ltd,22.410359,0.000000,30.114485
7,Abbott India Ltd,24.393254,0.071987,29.037208
8,Abbott India Ltd,26.556495,0.058801,33.478577
9,Abbott India Ltd,28.333333,0.053901,36.418714
10,Abbott India Ltd,29.767880,0.035445,36.523319
11,Abbott India Ltd,32.468235,0.022438,38.418826
65,Adani Ports & Special Economic Zone Ltd\n,15.354883,0.937322,15.246264
66,Adani Ports & Special Economic Zone Ltd\n,15.354883,0.937322,15.246264
78,Adani Power Ltd,48.276741,0.802318,23.441057
99,Apollo Hospitals\nChain of Indian private hosp...,19.704784,0.723457,22.587968
102,Asian Paints\nIndian Multi-National Paint and ...,34.278960,0.074173,47.785420
103,Asian Paints\nIndian Multi-National Paint and ...,34.278960,0.074173,47.785420
104,Asian Paints\nIndian Multi-National Paint and ...,31.270116,0.061649,46.735075
105,Asian Paints\nIndian Multi-National Paint and ...,31.270116,0.061649,46.735075

SPRINT 2 RETROSPECTIVE
--------------------------------------------------------------------------------

,Formula,Decision,Edge Case
0,ROCE,Operating Profit / Capital Employed ×100,Compared with source values
1,ROE,Net Profit / Net Worth ×100,Source values retained for display
2,Debt to Equity,Borrowings / Net Worth,Suppressed for Financial companies
3,Capital Employed,Total Assets - Other Liabilities,Zero handled safely
4,Net Worth,Equity Capital + Reserves,Zero handled safely

FINANCIAL RATIOS DEMO
--------------------------------------------------------------------------------

       company_name  computed_roce  computed_roe  de_ratio de_warning
0  Abbott India Ltd      31.221020     22.411128       0.0     Normal
1  Abbott India Ltd      33.883249     25.126904       0.0     Normal
2  Abbott India Ltd      33.262260     24.439701       0.0     Normal
3  Abbott India Ltd      30.543933     21.338912       0.0     Normal
4  Abbott India Ltd      28.695025     19.971161       0.0     Normal

financial_ratios_demo.csv saved.

================================================================================
DAY 14 COMPLETED SUCCESSFULLY
================================================================================